apiVersion: batch/v1
kind: Job
metadata:
  name: coder-deploy-template
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: coder-deploy-template
          image: {{ .Subcharts.coder.Values.coder.image.repo }}:{{ .Subcharts.coder.Values.coder.image.tag }}
          command: ["/bin/bash", "/home/coder/init-files/init.sh"]
          env:
            {{- with .Subcharts.coder.Values.coder.env -}}
            {{ toYaml . | nindent 12 }}
            {{- end }}  
            - name: CODER_ACCESS_URL
              value: "http://coder"
            - name: CODER_URL
              value: "http://coder"
            - name: CODER_FIRST_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: coder-user
                  key: username
            - name: CODER_FIRST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coder-user
                  key: password
            - name: CODER_FIRST_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: coder-user
                  key: email
            - name: CODER_FIRST_USER_TRIAL
              value: "false"
          volumeMounts:
          - name: init-files
            mountPath: "/home/coder/init-files"
            readOnly: true
          - name: custom-template
            mountPath: "/home/coder/custom-template"
            readOnly: true
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12}}
      restartPolicy: Never
      volumes:
        - name: init-files
          configMap:
            name: coder-init
        - name: custom-template
          configMap:
            name: coder-custom-template

