apiVersion: v2
name: kubernetes-resource-manager
description: A Helm chart for Kubernetes
type: application
version: 0.1.22
appVersion: "1.1.18"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
