apiVersion: v2
name: core
description: Core backend application for DigitalHub.
type: application
version: 0.1.26
appVersion: "0.5.0-beta1"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
