apiVersion: v2
name: core
description: Core backend application for DigitalHub.
type: application
version: 0.1.35
appVersion: "0.6.0"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
