apiVersion: v2
name: digitalhub
description: The Digital Hub is an open-source platform for interoperability of data and services, built by integrating several open-source projects to manage, elaborate, expose and serve data through modern standards.
type: application
maintainers:
  - name: scc-digitalhub
    url: https://github.com/scc-digitalhub
version: 0.2.54
appVersion: "0.3.0"
dependencies:
- name: docker-registry
  version: "2.2.2"
  repository: "https://helm.twun.io"
  condition: docker-registry.enabled
- name: mlrun-ce
  version: "0.6.3-rc3"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: mlrun-ce.enabled
- name: coder
  version: "0.1.0"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: coder.enabled
- name: postgres-operator
  version: "1.10.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
  condition: postgres-operator.enabled
- name: ext-postgres-operator
  version: "1.2.4"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: ext-postgres-operator.enabled
- name: custom-resource-manager
  version: "0.1.0"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: custom-resource-manager.enabled
- name: postgrest-operator
  version: "0.1.0"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: postgrest-operator.enabled
- name: grafana
  version: "7.0.3"
  repository: "https://grafana.github.io/helm-charts"
  condition: grafana.enabled
- name: core
  version: "0.1.5"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: core.enabled
- name: apigw-operator
  version: "0.1.2"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: apigw-operator.enabled
- name: rabbitmq-cluster-operator
  version: "3.10.10"
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq-cluster-operator.enabled
- name: dremio-rest-server-operator
  version: "0.1.1"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: dremio-rest-server-operator.enabled
- name: airflow
  version: "8.8.1"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: airflow.enabled
- name: opensearch
  version: "2.12.1"
  repository: "https://opensearch-project.github.io/helm-charts/"
  condition: opensearch.enabled
- name: openmetadata
  repository: https://helm.open-metadata.org
  version: 1.2.8
  condition: openmetadata.enabled
- name: openmetadata-java-connector
  version: 0.1.6
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: openmetadata-java-connector.enabled
  