# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: ConfigMap
metadata:
  name: code-toolbox-init
data:
  {{- range .Values.coder.template.customTemplates }}
  {{- if eq .name "code-toolbox" }}
  tolerations.json: {{ .tolerations | toJson | quote }}
  {{- end }}
  {{- end }}
  run.sh: | {{- tpl (.Files.Get "confs/code-toolbox/run.sh") . | nindent 4 }}
