# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: postgrests.operator.postgrest.org
spec:
  group: operator.postgrest.org
  names:
    kind: Postgrest
    listKind: PostgrestList
    plural: postgrests
    singular: postgrest
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Schema for the postgrests API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PostgREST properties
            properties:
              anonRole:
                description: Role used by PostgREST to authenticate on the database;
                  if not specified, it will be auto-generated as <CR name>_postgrest_role'
                type: string
              connection:
                description: Properties to connect to Postgres
                properties:
                  database:
                    type: string
                  extraParams:
                    description: Additional connection properties as query parameters
                      (e.g., sslmode=disable)
                    type: string
                  host:
                    type: string
                  password:
                    type: string
                  port:
                    type: integer
                  secretName:
                    description: Alternative to user and password properties; secret
                      will have to contain USER and PASSWORD, optionally POSTGRES_URL
                    type: string
                  user:
                    type: string
                type: object
              grants:
                description: Comma-separated string of permitted actions (only if
                  anonymous role is auto-generated)
                type: string
              schema:
                description: Schema for this PostgREST instance
                type: string
              tables:
                description: Tables to expose (only if anonymous role is auto-generated)
                items:
                  type: string
                type: array
            type: object
          status:
            description: PostgREST status
            properties:
              generatedAnonRole:
                type: string
              state:
                type: string
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
