# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if and .Values.seaweedfs.enabled (not .Values.global.s3.argo.existingSecret.secretName) -}}
apiVersion: v1
data:
  accesskey: {{ .Values.global.s3.argo.accessKey | b64enc }}
  secretkey: {{ .Values.global.s3.argo.secretKey | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.s3.argo.secretName }}
type: Opaque
{{- end }}
