# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if and .Values.seaweedfs.enabled (not .Values.global.s3.platform.existingSecret.secretName) -}}
apiVersion: v1
data:
  accessKey: {{ .Values.global.s3.platform.accessKey | b64enc }}
  secretKey: {{ .Values.global.s3.platform.secretKey | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.s3.platform.platformUserSecret }}
type: Opaque
{{- end }}
