# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: dremiorestservers.operator.dremiorestserver.com
spec:
  group: operator.dremiorestserver.com
  names:
    kind: DremioRestServer
    listKind: DremioRestServerList
    plural: dremiorestservers
    singular: dremiorestserver
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Schema for the dremiorestservers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Dremio REST Server properties
            properties:
              connection:
                description: Properties to connect to Dremio
                properties:
                  host:
                    type: string
                  jdbcProperties:
                    description: 'Additional JDBC options supported by the Arrow Flight
                      SQL JDBC driver that will be passed as query parameters (e.g.:
                      useEncryption=false&disableCertificateVerification=true)'
                    type: string
                  password:
                    type: string
                  port:
                    type: integer
                  secretName:
                    description: Alternative to user and password properties; secret
                      will have to contain USER and PASSWORD
                    type: string
                  user:
                    type: string
                type: object
              tables:
                description: Comma-separated list of tables to expose
                type: string
            type: object
          status:
            description: Dremio REST Server status
            properties:
              state:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
