apiVersion: v2
name: custom-resource-manager
description: A Helm chart for Kubernetes
type: application
version: 0.1.7
appVersion: "1.1.5"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
