# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: postgrest-operator
description: A Kubernetes operator to start instances of PostgREST.
home: "https://github.com/scc-digitalhub/digitalhub/tree/main/charts/postgrest-operator"
type: application
version: 0.1.9
appVersion: "2.0.5"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
sources:
  - https://github.com/scc-digitalhub/postgrest-operator
