# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if (index .Values "template-controller" "objectTemplate" "enabled") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-transformer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-transformer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-transformer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-transformer
subjects:
  - kind: ServiceAccount
    name: secret-transformer
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-transformer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-transformer
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-transformer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-transformer
subjects:
  - kind: ServiceAccount
    name: configmap-transformer
    namespace: {{ .Release.Namespace }}
{{- end }}
