# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.coder.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: coder-deploy-template
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: coder-deploy-template
          image: {{ .Subcharts.coder.Values.coder.image.repo }}:{{ .Subcharts.coder.Values.coder.image.tag }}
          command: ["/bin/bash", "/home/coder/init-files/init.sh"]
          env:
            {{- with .Subcharts.coder.Values.coder.env -}}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            {{- include "digitalhub.coderAccUrl" . | nindent 12 -}}
            - name: CODER_URL
              value: "http://coder"
            - name: CODER_FIRST_USER_USERNAME
              {{- if and .Values.coder.existingSecrets.adminUserExistingSecret.secretName .Values.coder.existingSecrets.adminUserExistingSecret.usernameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.coder.existingSecrets.adminUserExistingSecret.secretName }}
                  key: {{ .Values.coder.existingSecrets.adminUserExistingSecret.usernameKey }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: coder-user
                  key: username
              {{- end }}
            - name: CODER_FIRST_USER_PASSWORD
              {{- if and .Values.coder.existingSecrets.adminUserExistingSecret.secretName .Values.coder.existingSecrets.adminUserExistingSecret.passwordKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.coder.existingSecrets.adminUserExistingSecret.secretName }}
                  key: {{ .Values.coder.existingSecrets.adminUserExistingSecret.passwordKey }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: coder-user
                  key: password
              {{- end }}
            - name: CODER_FIRST_USER_EMAIL
              {{- if and .Values.coder.existingSecrets.adminUserExistingSecret.secretName .Values.coder.existingSecrets.adminUserExistingSecret.emailKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.coder.existingSecrets.adminUserExistingSecret.secretName }}
                  key: {{ .Values.coder.existingSecrets.adminUserExistingSecret.emailKey }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: coder-user
                  key: email
              {{- end }}
            - name: CODER_FIRST_USER_TRIAL
              value: "false"
          volumeMounts:
          - name: init-files
            mountPath: "/home/coder/init-files"
            readOnly: true
          - name: custom-template
            mountPath: "/home/coder/custom-template"
            readOnly: true
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: init-files
          configMap:
            name: coder-init
        - name: custom-template
          configMap:
            name: coder-custom-template
{{- end }}
