apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: external-dns
spec:
  clusterSelector:
    matchLabels:
      cloud-provider: azure
      app: digitalhub
      env: test
  repoURL: https://kubernetes-sigs.github.io/external-dns/
  chartName: external-dns
  namespace: external-dns
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    sources:
      - ingress
    provider: azure
    extraArgs:
      - --azure-resource-group=${RESOURCE_GROUP}
      - --txt-wildcard-replacement=wildcard
    secretConfiguration:
      enabled: true
      mountPath: "/etc/kubernetes/"
      data:
        azure.json: |
          {
            "tenantId": "${TENANT_ID}",
            "subscriptionId": "${SUBSCRIPTION_ID}",
            "resourceGroup": "${RESOURCE_GROUP}",
            "useManagedIdentityExtension": true,
          }